version: '2'

services:
  kafka:
    image: wurstmeister/kafka
    hostname: kafka
    ports:
    - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.225.60:9092
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: 192.168.225.60:2181